-- 学生都选了什么课（把列换成行显示）
-- set group_concat_max_len=10000;
SELECT 
    S.NAME,
    GROUP_CONCAT(C.NAME ORDER BY C.NAME ) AS COURSES
FROM 
    STUDENT AS S,
    COURSE AS C,
    STUDENT_COURSE_MAP AS M
WHERE 
    S.ID = M.STUDENT_ID
    AND C.ID = M.COURSE_ID
GROUP BY S.NAME
HAVING COUNT(C.NAME)>1;

-- 把各科考试，前三名取出来。
-- MYSQL 没有 ROW_NUMBER() OVER(PARTITION BY A ORDER BY B DESC)
SELECT 
    C.NAME AS COURSE, 
    S.NAME AS STUDENT, 
    E.SCORE 
FROM 
    EXAM AS E ,
    STUDENT AS S,
    COURSE AS C
WHERE 
    (SELECT COUNT(*) FROM EXAM AS B WHERE B.COURSE_ID = E.COURSE_ID AND B.SCORE >= E.SCORE) <= 3 
    AND E.STUDENT_ID = S.ID
    AND E.COURSE_ID = C.ID
ORDER BY COURSE ASC, SCORE DESC;

SELECT * FROM STUDENT 
WHERE (ID,NAME) IN ((1,'学生1'),(2,'学生2'));

-- ------- 增 ----------
SELECT * FROM COURSE;

INSERT IGNORE INTO COURSE (ID,NAME) 
VALUES 
(1,'课程1'),
(11,'课程1'),
(5,'课程5'),
(6,'课程6');

REPLACE INTO COURSE (ID,NAME) 
VALUES 
(5,'课程55'),
(66,'课程6'),
(7,'课程7');

INSERT INTO COURSE (ID,NAME) 
VALUES (5,'课程5'),(6,'课程6'),(8,'课程6')
ON DUPLICATE KEY UPDATE
    NAME=VALUES(NAME),ID=VALUES(ID);

INSERT INTO COURSE (ID,NAME) 
VALUES (5,'课程5'),(6,'课程6'),(7,'课程7')
ON DUPLICATE KEY UPDATE
    NAME=VALUES(NAME),
    ID=(CASE WHEN NAME = VALUES(NAME)
        THEN VALUES(ID)
        ELSE ID
        END);

-- 删

SELECT * FROM AUTOINCR_1;

SELECT * FROM AUTOINCR_2;

CREATE TABLE AUTOINCR_1 LIKE AUTOINCR; -- 表结构相同
INSERT INTO AUTOINCR_1 SELECT * FROM AUTOINCR;
DESCRIBE AUTOINCR_1;

CREATE TABLE AUTOINCR_2 SELECT * FROM AUTOINCR WHERE ID <10; -- 不相同
DESCRIBE AUTOINCR_2;

DELETE FROM AUTOINCR_1;
INSERT INTO AUTOINCR_1 (NAME) VALUES ('课程1');
TRUNCATE TABLE AUTOINCR_1;

DELETE T1,T2 
FROM AUTOINCR_1 AS T1,AUTOINCR_2 AS T2
WHERE T1.ID = T2.ID;

DELETE QUICK FROM AUTOINCR_2;
OPTIMIZE TABLE AUTOINCR_2;

-- 改 ------
INSERT INTO AUTOINCR_1 SELECT ID,NULL FROM AUTOINCR;
INSERT INTO AUTOINCR_2 SELECT * FROM AUTOINCR WHERE ID <10;

-- 更新单个字段
UPDATE AUTOINCR_2 AS T2, AUTOINCR_1 AS T1
SET T1.NAME = T2.NAME 
WHERE T2.ID = T1.ID;

UPDATE AUTOINCR_1 SET NAME=NULL;
UPDATE AUTOINCR_1 AS T1
SET T1.NAME = (SELECT T2.NAME FROM AUTOINCR_2 AS T2 WHERE T2.ID = T1.ID);

CREATE TABLE STUDENT_1 LIKE STUDENT;
INSERT INTO STUDENT_1 SELECT ID,CONCAT(NAME,'#'),0 FROM STUDENT;

SELECT * FROM STUDENT;

SELECT * FROM STUDENT_1;

-- 更新多个字段
UPDATE STUDENT_1 AS T1
INNER JOIN (SELECT T.ID, T.NAME,  T.GENDER FROM STUDENT AS T) AS T2 
ON T2.ID = T1.ID
SET T1.NAME = T2.NAME ,T1.GENDER = T2.GENDER;